FROM mysite

WORKDIR /testing

COPY Pipfile* /testing/

RUN pipenv install --dev --system

COPY setup.py /testing/

RUN pip install -e .[testing]

# since we're mounting the code for our tests as a volume
# we need to remove bytecode on execution

CMD find . -name *.pyc -delete && pytest tests/

