version: "3"

services:

  web:
    build: .
    image: mysite
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/workdir/mysite
    depends_on:
      - migration

  migration:
    image: mysite
    volumes:
      - ./mysite:/workdir/mysite
    command: python mysite/manage.py migrate
    depends_on:
      - db

  db:
    image: postgres

  tests:
    image: mysite.test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./mysite:/workdir/mysite
      - ./tests:/workdir/tests